name: Sync Azure DevOps to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add Azure DevOps remote
        run: git remote add azure <URL-of-your-Azure-repo>

      - name: Fetch from Azure DevOps
        run: git fetch azure

      - name: Push to GitHub
        run: git push github --all
