name: Sync Azure DevOps to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'manhalshiha'
          git config --global user.email 'manhal6@gmail.com'

      - name: Add Azure DevOps remote
        run: git remote add azure ${{https://manhal6Official@dev.azure.com/manhal6Official/MicroServicesSmartSchool/_git/SmartSchool }}

      - name: Fetch from Azure DevOps
        run: git fetch azure

      - name: Push to GitHub
        run: git push origin --all
